global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files: []

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ingestion'
    static_configs:
      - targets: ['ingestion:8000']
    metrics_path: /metrics

  - job_name: 'api'
    static_configs:
      - targets: ['api:8001']
    metrics_path: /metrics

  - job_name: 'worker'
    static_configs:
      - targets: ['worker:9100']
    metrics_path: /metrics
